authenticate/urls.py
from django.urls import path
from . import views
app_name = "auth_app"

urlpatterns =[
    path("signup", views.SignupCreateView.as_view(), name="signup")
]

blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog_app'
urlpatterns = [
    path("", views.IndexPageTemplateView.as_view(), name="home"),
    path("posts/", views.BlogPostListView.as_view(), name="blog_list"),
    path("post/<int:pk>/", views.BlogPostDetailView.as_view(), name="blog_detail"),
    path("post/create/", views.BlogPostCreateView.as_view(), name="blog_create"),
    path("post/edit/<int:pk>/", views.BlogPostEditView.as_view(), name="blog_update"),
    path("post/delete/<int:pk>/", views.BlogPostDeleteView.as_view(), name="blog_delete")
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.IndexPageTemplateView.as_view(), name="home"),
    path("blogapp/", include('blog.urls')),
    path("auth/", include("django.contrib.auth.urls"), name="login_and_logout_user"),
    path("auth/", include("authenticate.urls"))
]

authenticate/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse_lazy
# Create your models here.


class BlogPost(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("blog_app:blog_detail", args=[str(self.pk)])

authenticate/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
# Create your views here.

class SignupCreateView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "blog_post_signup.html"

blog/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView, DetailView)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import BlogPost
# Create your views here.


class IndexPageTemplateView(ListView):
    model = BlogPost
    template_name = 'home.html'
    context_object_name = "posts"

class BlogPostListView(LoginRequiredMixin, ListView):
    model = BlogPost
    template_name = "blog_post_list.html"
    context_object_name = "posts"


class BlogPostDetailView(LoginRequiredMixin, DetailView):
    model = BlogPost
    template_name = "blog_post_detail.html"
    context_object_name = "post"


class BlogPostCreateView(LoginRequiredMixin, CreateView):
    model = BlogPost
    template_name = "blog_post_create.html"
    fields = "__all__"


class BlogPostEditView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    template_name = "blog_post_update.html"
    fields = ("title", "body")


class BlogPostDeleteView(LoginRequiredMixin, DeleteView):
    model = BlogPost
    template_name = "blog_post_delete.html"
    success_url = reverse_lazy("blog_list")

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django Blog</title>
    <link rel="stylesheet" href="{% static 'blog_post.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'blog_app:blog_list' %}">Home</a>
        {% else %}
            <a class="navbar-brand" href="{% url 'blog_app:home' %}">Home</a>
        {% endif %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog_app:blog_create' %}">Create Post</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item" ><span class="navbar-text" style="color:white;">Welcome {{user.username}}</span></li>
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link" style="color:black">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'login' %}" class="nav-link" style="color:white">Login</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'auth_app:signup' %}" class="nav-link" style="color:white">Signup</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
    
</body>
</html>

templates/blog_post_create.html
{% extends 'base.html' %}
{% block body_block %}
    <h1>Create New Blog</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" class="btn btn-primary">
    </form>
{% endblock body_block %}

templates/blog_post_delete.html
{% extends 'base.html' %}
{% block body_block %}
<br><br>
    <h1>Delete Blog</h1>
    <br><br>
    <form method="POST">
        {% csrf_token %}
        <h1>Are you sure you wanna delete {{post.title}} ??</h1>
        <br><br>
        <input type="submit" value="Confirm" class="btn btn-primary">
        <a href="{% url 'blog_list' %}">Cancel</a>
    </form>
{% endblock body_block %}

templates/blog_post_detail.html
{% extends 'base.html' %}
{% block body_block %}
<br><br>
<div class="post">
    <h1>{{post.title}}</h1>
    <br><br>
    <h2>{{post.body}}</h2>
</div>
<br><br>
<a href="{% url 'blog_app:blog_update' post.pk %}" class="btn btn-warning">Edit Post</a>
<a href="{% url 'blog_app:blog_delete' post.pk %}" class="btn btn-danger">Delete Post</a>
{% endblock body_block %}

templates/blog_post_list.html
{% extends 'base.html' %}
{% block body_block %}
    {% if posts %}
        <h1>ALL BLOGS</h1>
        {% for post in posts %}
            <div class="post">
                <h2><a href="{% url 'blog_app:blog_detail' post.pk %}">{{post.title}}</a></h2>
            </div>
        {% endfor %}
    {% else %}
        <h1>There are no Posts to display</h1>
    {% endif %}
{% endblock body_block %}

templates/blog_post_signup.html
{% extends 'base.html' %}
{% block body_block %}
<h1>New user Signup</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Signup" class="btn btn-primary">
</form>
{% endblock body_block %}

templates/blog_post_update.html
{% extends 'base.html' %}
{% block body_block %}
    <h1>Update Blog</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-success">
    </form>
{% endblock body_block %}

templates/home.html
{% extends 'base.html' %}
{% block body_block %}
    {% if user.is_authenticated %}
        {% if posts %}
            <h1>ALL BLOGS</h1>
            {% for post in posts %}
                <div class="post">
                    <h2><a href="{% url 'blog_app:blog_detail' post.pk %}">{{post.title}}</a></h2>
                </div>
            {% endfor %}
        {% else %}
            <h1>There are no Posts to display</h1>
        {% endif %}
    {% else %}
        <h1>Please Login to see all posts</h1>
    {% endif %}
{% endblock %}